databases:
  - name: bizmeddb
    databaseName: bizmed
    user: bizuser
    plan: free
    ipAllowList: []

services:
  - type: web
    name: bizmed-service
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bizmeddb
          property: connectionString
